//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The100AutoMod.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The100AutoMod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $( &apos;#gamertag&apos; ).val( &apos;{username}&apos; );
        ///$( &apos;#password&apos; ).val( &apos;{password}&apos; );
        ///$( &apos;input[type=\&quot;submit\&quot;][name=\&quot;commit\&quot;]&apos; ).click();.
        /// </summary>
        internal static string The100Browser_LoginScript {
            get {
                return ResourceManager.GetString("The100Browser_LoginScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( function()
        ///{
        ///    var target = document.querySelector( &quot;ul.messages&quot; );
        ///
        ///    if( target )
        ///    {
        ///        var config = { childList: true };
        ///
        ///        var loadedTime = new Date().getTime();
        ///
        ///        var observer = new MutationObserver( function( mutations )
        ///        {
        ///            mutations.forEach( function( mutation )
        ///            {
        ///                mutation.addedNodes.forEach( function( addedNode )
        ///                {
        ///                    var username = addedNode.dataset.from;
        ///                     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string The100ChatBrowser_CreateChatListenerScript {
            get {
                return ResourceManager.GetString("The100ChatBrowser_CreateChatListenerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( function()
        ///{
        ///    var lastMessage = document.querySelector( &apos;[data-from=&quot;D633_Automod&quot;]&apos; );
        ///    if( !lastMessage )
        ///    {
        ///        throw &apos;Could not find last message.&apos;;
        ///    }
        ///
        ///    var editLink = lastMessage.querySelector( &apos;a.edit-message&apos; );
        ///    if( !editLink )
        ///    {
        ///        throw &apos;Could not find edit link for last message.&apos;;
        ///    }
        ///
        ///    editLink.click();
        ///
        ///    var editMessageInput = document.querySelector( &apos;form.edit-message input.inputMessage&apos; );
        ///    if( !editMessageInput )
        ///    {
        ///        t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string The100ChatBrowser_EditLastMessage {
            get {
                return ResourceManager.GetString("The100ChatBrowser_EditLastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( function()
        ///{
        ///    var chatMessageInput = document.querySelector( &apos;#chatroom .inputMessage&apos; );
        ///    if( !chatMessageInput )
        ///    {
        ///        throw &apos;Could not find chat message input.&apos;;
        ///    }
        ///
        ///    var chatMessageSubmit = document.querySelector( &apos;#chatSubmit&apos; );
        ///    if( !chatMessageSubmit )
        ///    {
        ///        throw &apos;Could not find chat message submit button.&apos;;
        ///    }
        ///
        ///    chatMessageInput.value = `{chatMessage}`;
        ///    chatMessageSubmit.click();
        ///} )();.
        /// </summary>
        internal static string The100ChatBrowser_SendChatMessage {
            get {
                return ResourceManager.GetString("The100ChatBrowser_SendChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( function()
        ///{
        ///    var homePageHtmlInput = document.getElementById( &apos;html&apos; );
        ///    if( !homePageHtmlInput )
        ///    {
        ///        throw &apos;Could not find home page html input.&apos;;
        ///    }
        ///
        ///    function waitForHomePageHtml()
        ///    {
        ///        if( homePageHtmlInput.value )
        ///        {
        ///            The100BoundMod.onHomePageHtmlReceived( homePageHtmlInput.value );
        ///        }
        ///        else
        ///        {
        ///            setTimeout( waitForHomePageHtml, 100 );
        ///        }
        ///    }
        ///    
        ///    waitForHomePageHtml();
        ///
        ///} )();.
        /// </summary>
        internal static string The100ModBrowser_GetHomePageHtml {
            get {
                return ResourceManager.GetString("The100ModBrowser_GetHomePageHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( function()
        ///{
        ///    var homePageHtmlInput = document.getElementById( &apos;group_latest_news_html&apos; );
        ///    if( !homePageHtmlInput )
        ///    {
        ///        throw &apos;Failed to find &quot;Latest New HTML&quot; input.&apos;;
        ///    }
        ///
        ///    homePageHtmlInput.value = `{homePageHtml}`;
        ///
        ///    var submitButton = document.querySelector( &apos;#edit_group_268 input[type=&quot;submit&quot;]&apos; );
        ///    if( !submitButton )
        ///    {
        ///        throw &apos;Failed to find Submit button.&apos;;
        ///    }
        ///
        ///    submitButton.click();
        ///} )();.
        /// </summary>
        internal static string The100ModBrowser_SetHomePageHtml {
            get {
                return ResourceManager.GetString("The100ModBrowser_SetHomePageHtml", resourceCulture);
            }
        }
    }
}
